---
- name: "enshure created {{ gitlab_git_user.comment }}"
  user: state=present
        name={{ gitlab_git_user.name }} comment="{{ gitlab_git_user.comment }}"
        home={{ gitlab_git_user.home }} groups={{ gitlab_git_user.groups }}
        generate_ssh_key=yes
  sudo: true
  tags:
    - gitlab

  # /var/git/.ssh
- name: enshure created {{ gitlab_git_user.comment }} .ssh directory
  file: state=directory
        path={{ gitlab_git_user.home }}/.ssh mode=700
        owner={{ gitlab_git_user.name }} group={{ gitlab_git_user.name }}
  sudo: true
  tags:
    - gitlab
