---
- name: include env global vars
  include_vars:
    "{{ gitlab_type }}.yml"

- name: include env spec vars
  include_vars:
    "{{ gitlab_env }}-{{ gitlab_type }}.yml"

- name: Install packages
  include: packages.yml

- name: run common steps
  include: common.yml

- name: include gitlabhq tasks
  include: gitlabhq.yml
  when: not "{{ gitlab_type }}" != "gitlabhq"

- name: include upstream tasks
  include: gitlab-undev.yml
  when: not "{{ gitlab_type }}" != "undev"

- name: run db setup
  include: databases.yml

- name: run nginx configure
  include: nginx.yml

- name: run runit steps
  include: runit.yml
  when: not "{{ gitlab_type }}" != "undev"
