---
- name: "enshure created {{ item.comment }}"
  user: state=present
        name={{ item.name }} comment="{{ item.comment }}"
        home={{ item.home }} groups={{ item.groups }}
        generate_ssh_key=yes
  sudo: true
  with_items:
    - $gitlab_deploy_user
  tags:
    - gitlab

  # /var/git/.ssh
  # /home/gitlab/.ssh
- name: enshure created {{ item.comment }} .ssh directory
  file: state=directory path={{ item.home }}/.ssh owner={{ item.name }} group={{ item.name }} mode=700
  sudo: true
  with_items:
    - $gitlab_deploy_user
  tags:
    - gitlab

  # /home/gitlab/.ssh/authorized_keys
- name: Upload SSH authorized_keys for {{ item.comment }}.
  copy: src=authorized_keys dest={{ item.home}}/.ssh/authorized_keys owner={{ item.name }} group={{ item.name }} mode=0600
  sudo: true
  with_items:
    - $gitlab_deploy_user
  when: not "{{ gitlab_deploy_user.name }}" == "{{ gitlab_git_user.name }}"
  tags:
    - gitlab

  # /rest/u/apps/gitlab
  # /rest/u/apps/gitlab/releases
  # /rest/u/apps/gitlab/shared
  # /rest/u/apps/gitlab/shared/gitlab-satellites
  # /rest/u/apps/gitlab/shared/uploads
  # /rest/u/apps/gitlab/log
  # /rest/u/apps/gitlab/system
  # /rest/u/apps/gitlab/pids
- name: create project directory
  file: state=directory path={{ item.path }} owner={{ item.owner }} group={{ item.group }}
  with_items:
    - $gitlab_web_base_dir
    - $gitlab_web_releases_dir
    - $gitlab_web_shared_dir
    - $gitlab_web_satellites_dir
    - $gitlab_web_uploads_dir
    - $gitlab_web_log_dir
    - $gitlab_web_system_dir
    - $gitlab_web_pids_dir
    - $gitlab_shell_base_dir
    - $gitlab_shell_releases_dir
  sudo: true
  tags:
    - gitlab
