---
gitlab_env:         production
gitlab_server:      puma

gitlab_web_repo:    "git://github.com/Undev/gitlabhq.git"
gitlab_web_branch:  'master'
gitlab_web_version: '6.4'
gitlab_web_domains: ["gitlab.production.host"]

gitlab_web_databases:
  - { adapter: postgresql,
      user: gitlab,
      password: '',
      name: gitlab_production,
      role_attr_flags: 'NOSUPERUSER,NOCREATEDB',
      locale: "en_US.UTF-8",
      encoding: "UTF-8" }

gitlab_runit_services:
  - { service: sidekiq,               name: main,   queue: "post_receive,build_result,project_web_hook,system_hook,common,default", concurency: 5 }
  - { service: sidekiq,               name: mail,   queue: "mail_notifications,mailer", concurency: 10 }
  - { service: sidekiq,               name: shell,  queue: "gitlab_shell", concurency: 3 }
  - { service: "{{ gitlab_server }}", name: web,    port: "{{ gitlab_web_web_port }}", workers: 3, backlog: 1000 }
  - { service: "{{ gitlab_server }}", name: api,    port: "{{ gitlab_web_api_port }}", workers: 3, backlog: 1000 }
